name: Build and Deploy to ECS



on:
  push:
    branches:
      - main  # Adjust this if you want to trigger on a different branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Send Discord Notification - Commit Details
        run: |
          commit_message=$(git log -1 --pretty=%B)
          curl -X POST -H "Content-Type: application/json" -d '{"content": "New commit: '"$commit_message"'"}' ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Send Discord Notification - Docker login
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "Logged in to Docker Hub."}' ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: chimmon/sports-api:latest

      - name: Send Discord Notification - Docker Build
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "Docker image built and pushed to latest version!"}' ${{ secrets.DISCORD_WEBHOOK_URL }}


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}


      - name: Update ECS Service (Force New Deployment)
        run: |
          aws ecs update-service --cluster api --service api-service --force-new-deployment

      - name: Send Discord Notification - Deploy Completed
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "Deploy completed successfully!"}' ${{ secrets.DISCORD_WEBHOOK_URL }}
